require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClassificationsController do

  # This should return the minimal set of attributes required to create a valid
  # Classification. As you add validations to Classification, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all classifications as @classifications" do
      classification = Classification.create! valid_attributes
      get :index
      assigns(:classifications).should eq([classification])
    end
  end

  describe "GET show" do
    it "assigns the requested classification as @classification" do
      classification = Classification.create! valid_attributes
      get :show, :id => classification.id.to_s
      assigns(:classification).should eq(classification)
    end
  end

  describe "GET new" do
    it "assigns a new classification as @classification" do
      get :new
      assigns(:classification).should be_a_new(Classification)
    end
  end

  describe "GET edit" do
    it "assigns the requested classification as @classification" do
      classification = Classification.create! valid_attributes
      get :edit, :id => classification.id.to_s
      assigns(:classification).should eq(classification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Classification" do
        expect {
          post :create, :classification => valid_attributes
        }.to change(Classification, :count).by(1)
      end

      it "assigns a newly created classification as @classification" do
        post :create, :classification => valid_attributes
        assigns(:classification).should be_a(Classification)
        assigns(:classification).should be_persisted
      end

      it "redirects to the created classification" do
        post :create, :classification => valid_attributes
        response.should redirect_to(Classification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved classification as @classification" do
        # Trigger the behavior that occurs when invalid params are submitted
        Classification.any_instance.stub(:save).and_return(false)
        post :create, :classification => {}
        assigns(:classification).should be_a_new(Classification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Classification.any_instance.stub(:save).and_return(false)
        post :create, :classification => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested classification" do
        classification = Classification.create! valid_attributes
        # Assuming there are no other classifications in the database, this
        # specifies that the Classification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Classification.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => classification.id, :classification => {'these' => 'params'}
      end

      it "assigns the requested classification as @classification" do
        classification = Classification.create! valid_attributes
        put :update, :id => classification.id, :classification => valid_attributes
        assigns(:classification).should eq(classification)
      end

      it "redirects to the classification" do
        classification = Classification.create! valid_attributes
        put :update, :id => classification.id, :classification => valid_attributes
        response.should redirect_to(classification)
      end
    end

    describe "with invalid params" do
      it "assigns the classification as @classification" do
        classification = Classification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Classification.any_instance.stub(:save).and_return(false)
        put :update, :id => classification.id.to_s, :classification => {}
        assigns(:classification).should eq(classification)
      end

      it "re-renders the 'edit' template" do
        classification = Classification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Classification.any_instance.stub(:save).and_return(false)
        put :update, :id => classification.id.to_s, :classification => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested classification" do
      classification = Classification.create! valid_attributes
      expect {
        delete :destroy, :id => classification.id.to_s
      }.to change(Classification, :count).by(-1)
    end

    it "redirects to the classifications list" do
      classification = Classification.create! valid_attributes
      delete :destroy, :id => classification.id.to_s
      response.should redirect_to(classifications_url)
    end
  end

end
