require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EthnicitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Ethnicity. As you add validations to Ethnicity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ethnicities as @ethnicities" do
      ethnicity = Ethnicity.create! valid_attributes
      get :index
      assigns(:ethnicities).should eq([ethnicity])
    end
  end

  describe "GET show" do
    it "assigns the requested ethnicity as @ethnicity" do
      ethnicity = Ethnicity.create! valid_attributes
      get :show, :id => ethnicity.id.to_s
      assigns(:ethnicity).should eq(ethnicity)
    end
  end

  describe "GET new" do
    it "assigns a new ethnicity as @ethnicity" do
      get :new
      assigns(:ethnicity).should be_a_new(Ethnicity)
    end
  end

  describe "GET edit" do
    it "assigns the requested ethnicity as @ethnicity" do
      ethnicity = Ethnicity.create! valid_attributes
      get :edit, :id => ethnicity.id.to_s
      assigns(:ethnicity).should eq(ethnicity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ethnicity" do
        expect {
          post :create, :ethnicity => valid_attributes
        }.to change(Ethnicity, :count).by(1)
      end

      it "assigns a newly created ethnicity as @ethnicity" do
        post :create, :ethnicity => valid_attributes
        assigns(:ethnicity).should be_a(Ethnicity)
        assigns(:ethnicity).should be_persisted
      end

      it "redirects to the created ethnicity" do
        post :create, :ethnicity => valid_attributes
        response.should redirect_to(Ethnicity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ethnicity as @ethnicity" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ethnicity.any_instance.stub(:save).and_return(false)
        post :create, :ethnicity => {}
        assigns(:ethnicity).should be_a_new(Ethnicity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ethnicity.any_instance.stub(:save).and_return(false)
        post :create, :ethnicity => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ethnicity" do
        ethnicity = Ethnicity.create! valid_attributes
        # Assuming there are no other ethnicities in the database, this
        # specifies that the Ethnicity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ethnicity.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ethnicity.id, :ethnicity => {'these' => 'params'}
      end

      it "assigns the requested ethnicity as @ethnicity" do
        ethnicity = Ethnicity.create! valid_attributes
        put :update, :id => ethnicity.id, :ethnicity => valid_attributes
        assigns(:ethnicity).should eq(ethnicity)
      end

      it "redirects to the ethnicity" do
        ethnicity = Ethnicity.create! valid_attributes
        put :update, :id => ethnicity.id, :ethnicity => valid_attributes
        response.should redirect_to(ethnicity)
      end
    end

    describe "with invalid params" do
      it "assigns the ethnicity as @ethnicity" do
        ethnicity = Ethnicity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ethnicity.any_instance.stub(:save).and_return(false)
        put :update, :id => ethnicity.id.to_s, :ethnicity => {}
        assigns(:ethnicity).should eq(ethnicity)
      end

      it "re-renders the 'edit' template" do
        ethnicity = Ethnicity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ethnicity.any_instance.stub(:save).and_return(false)
        put :update, :id => ethnicity.id.to_s, :ethnicity => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ethnicity" do
      ethnicity = Ethnicity.create! valid_attributes
      expect {
        delete :destroy, :id => ethnicity.id.to_s
      }.to change(Ethnicity, :count).by(-1)
    end

    it "redirects to the ethnicities list" do
      ethnicity = Ethnicity.create! valid_attributes
      delete :destroy, :id => ethnicity.id.to_s
      response.should redirect_to(ethnicities_url)
    end
  end

end
