require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HospitalsController do

  # This should return the minimal set of attributes required to create a valid
  # Hospital. As you add validations to Hospital, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all hospitals as @hospitals" do
      hospital = Hospital.create! valid_attributes
      get :index
      assigns(:hospitals).should eq([hospital])
    end
  end

  describe "GET show" do
    it "assigns the requested hospital as @hospital" do
      hospital = Hospital.create! valid_attributes
      get :show, :id => hospital.id.to_s
      assigns(:hospital).should eq(hospital)
    end
  end

  describe "GET new" do
    it "assigns a new hospital as @hospital" do
      get :new
      assigns(:hospital).should be_a_new(Hospital)
    end
  end

  describe "GET edit" do
    it "assigns the requested hospital as @hospital" do
      hospital = Hospital.create! valid_attributes
      get :edit, :id => hospital.id.to_s
      assigns(:hospital).should eq(hospital)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hospital" do
        expect {
          post :create, :hospital => valid_attributes
        }.to change(Hospital, :count).by(1)
      end

      it "assigns a newly created hospital as @hospital" do
        post :create, :hospital => valid_attributes
        assigns(:hospital).should be_a(Hospital)
        assigns(:hospital).should be_persisted
      end

      it "redirects to the created hospital" do
        post :create, :hospital => valid_attributes
        response.should redirect_to(Hospital.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hospital as @hospital" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hospital.any_instance.stub(:save).and_return(false)
        post :create, :hospital => {}
        assigns(:hospital).should be_a_new(Hospital)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hospital.any_instance.stub(:save).and_return(false)
        post :create, :hospital => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hospital" do
        hospital = Hospital.create! valid_attributes
        # Assuming there are no other hospitals in the database, this
        # specifies that the Hospital created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hospital.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hospital.id, :hospital => {'these' => 'params'}
      end

      it "assigns the requested hospital as @hospital" do
        hospital = Hospital.create! valid_attributes
        put :update, :id => hospital.id, :hospital => valid_attributes
        assigns(:hospital).should eq(hospital)
      end

      it "redirects to the hospital" do
        hospital = Hospital.create! valid_attributes
        put :update, :id => hospital.id, :hospital => valid_attributes
        response.should redirect_to(hospital)
      end
    end

    describe "with invalid params" do
      it "assigns the hospital as @hospital" do
        hospital = Hospital.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hospital.any_instance.stub(:save).and_return(false)
        put :update, :id => hospital.id.to_s, :hospital => {}
        assigns(:hospital).should eq(hospital)
      end

      it "re-renders the 'edit' template" do
        hospital = Hospital.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hospital.any_instance.stub(:save).and_return(false)
        put :update, :id => hospital.id.to_s, :hospital => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hospital" do
      hospital = Hospital.create! valid_attributes
      expect {
        delete :destroy, :id => hospital.id.to_s
      }.to change(Hospital, :count).by(-1)
    end

    it "redirects to the hospitals list" do
      hospital = Hospital.create! valid_attributes
      delete :destroy, :id => hospital.id.to_s
      response.should redirect_to(hospitals_url)
    end
  end

end
