require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MedicsController do

  # This should return the minimal set of attributes required to create a valid
  # Medic. As you add validations to Medic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all medics as @medics" do
      medic = Medic.create! valid_attributes
      get :index
      assigns(:medics).should eq([medic])
    end
  end

  describe "GET show" do
    it "assigns the requested medic as @medic" do
      medic = Medic.create! valid_attributes
      get :show, :id => medic.id.to_s
      assigns(:medic).should eq(medic)
    end
  end

  describe "GET new" do
    it "assigns a new medic as @medic" do
      get :new
      assigns(:medic).should be_a_new(Medic)
    end
  end

  describe "GET edit" do
    it "assigns the requested medic as @medic" do
      medic = Medic.create! valid_attributes
      get :edit, :id => medic.id.to_s
      assigns(:medic).should eq(medic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Medic" do
        expect {
          post :create, :medic => valid_attributes
        }.to change(Medic, :count).by(1)
      end

      it "assigns a newly created medic as @medic" do
        post :create, :medic => valid_attributes
        assigns(:medic).should be_a(Medic)
        assigns(:medic).should be_persisted
      end

      it "redirects to the created medic" do
        post :create, :medic => valid_attributes
        response.should redirect_to(Medic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved medic as @medic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medic.any_instance.stub(:save).and_return(false)
        post :create, :medic => {}
        assigns(:medic).should be_a_new(Medic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medic.any_instance.stub(:save).and_return(false)
        post :create, :medic => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested medic" do
        medic = Medic.create! valid_attributes
        # Assuming there are no other medics in the database, this
        # specifies that the Medic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Medic.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => medic.id, :medic => {'these' => 'params'}
      end

      it "assigns the requested medic as @medic" do
        medic = Medic.create! valid_attributes
        put :update, :id => medic.id, :medic => valid_attributes
        assigns(:medic).should eq(medic)
      end

      it "redirects to the medic" do
        medic = Medic.create! valid_attributes
        put :update, :id => medic.id, :medic => valid_attributes
        response.should redirect_to(medic)
      end
    end

    describe "with invalid params" do
      it "assigns the medic as @medic" do
        medic = Medic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medic.any_instance.stub(:save).and_return(false)
        put :update, :id => medic.id.to_s, :medic => {}
        assigns(:medic).should eq(medic)
      end

      it "re-renders the 'edit' template" do
        medic = Medic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medic.any_instance.stub(:save).and_return(false)
        put :update, :id => medic.id.to_s, :medic => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested medic" do
      medic = Medic.create! valid_attributes
      expect {
        delete :destroy, :id => medic.id.to_s
      }.to change(Medic, :count).by(-1)
    end

    it "redirects to the medics list" do
      medic = Medic.create! valid_attributes
      delete :destroy, :id => medic.id.to_s
      response.should redirect_to(medics_url)
    end
  end

end
