require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TherapiesController do

  # This should return the minimal set of attributes required to create a valid
  # Therapy. As you add validations to Therapy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all therapies as @therapies" do
      therapy = Therapy.create! valid_attributes
      get :index
      assigns(:therapies).should eq([therapy])
    end
  end

  describe "GET show" do
    it "assigns the requested therapy as @therapy" do
      therapy = Therapy.create! valid_attributes
      get :show, :id => therapy.id.to_s
      assigns(:therapy).should eq(therapy)
    end
  end

  describe "GET new" do
    it "assigns a new therapy as @therapy" do
      get :new
      assigns(:therapy).should be_a_new(Therapy)
    end
  end

  describe "GET edit" do
    it "assigns the requested therapy as @therapy" do
      therapy = Therapy.create! valid_attributes
      get :edit, :id => therapy.id.to_s
      assigns(:therapy).should eq(therapy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Therapy" do
        expect {
          post :create, :therapy => valid_attributes
        }.to change(Therapy, :count).by(1)
      end

      it "assigns a newly created therapy as @therapy" do
        post :create, :therapy => valid_attributes
        assigns(:therapy).should be_a(Therapy)
        assigns(:therapy).should be_persisted
      end

      it "redirects to the created therapy" do
        post :create, :therapy => valid_attributes
        response.should redirect_to(Therapy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved therapy as @therapy" do
        # Trigger the behavior that occurs when invalid params are submitted
        Therapy.any_instance.stub(:save).and_return(false)
        post :create, :therapy => {}
        assigns(:therapy).should be_a_new(Therapy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Therapy.any_instance.stub(:save).and_return(false)
        post :create, :therapy => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested therapy" do
        therapy = Therapy.create! valid_attributes
        # Assuming there are no other therapies in the database, this
        # specifies that the Therapy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Therapy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => therapy.id, :therapy => {'these' => 'params'}
      end

      it "assigns the requested therapy as @therapy" do
        therapy = Therapy.create! valid_attributes
        put :update, :id => therapy.id, :therapy => valid_attributes
        assigns(:therapy).should eq(therapy)
      end

      it "redirects to the therapy" do
        therapy = Therapy.create! valid_attributes
        put :update, :id => therapy.id, :therapy => valid_attributes
        response.should redirect_to(therapy)
      end
    end

    describe "with invalid params" do
      it "assigns the therapy as @therapy" do
        therapy = Therapy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Therapy.any_instance.stub(:save).and_return(false)
        put :update, :id => therapy.id.to_s, :therapy => {}
        assigns(:therapy).should eq(therapy)
      end

      it "re-renders the 'edit' template" do
        therapy = Therapy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Therapy.any_instance.stub(:save).and_return(false)
        put :update, :id => therapy.id.to_s, :therapy => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested therapy" do
      therapy = Therapy.create! valid_attributes
      expect {
        delete :destroy, :id => therapy.id.to_s
      }.to change(Therapy, :count).by(-1)
    end

    it "redirects to the therapies list" do
      therapy = Therapy.create! valid_attributes
      delete :destroy, :id => therapy.id.to_s
      response.should redirect_to(therapies_url)
    end
  end

end
